[package]
name = "vboot"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
cty = "0.2.2"
log = "0.4.0"
printf-compat = { version = "0.1.1", default-features = false }
uguid = "0.7.0"

[dev-dependencies]
regex = "1.5.6"
simple_logger = { version = "2.1.0", default-features = false }

[build-dependencies]
bindgen = "0.60.1"
camino = "1.0.9"
cc = "1.0.73"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
