[package]
name = "vboot"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = { version = "0.4.3", default-features = false, features = ["pe32", "pe64"] }
log = "0.4.14"
printf-compat = { version = "0.1.1", default-features = false }
scroll = { version = "0.11.0", default-features = false }

[build-dependencies]
bindgen = "0.59.2"
camino = "1.0.7"
cc = "1.0.72"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
