[package]
name = "vboot"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@google.com>"]
edition = "2018"

[dependencies]
sha2 = "0.9.5"
rsa = "0.4.0"

[build-dependencies]
bindgen = "0.58.1"
