[package]
name = "vboot"
version = "1.0.0"

edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cmem.workspace = true
log.workspace = true
printf-compat.workspace = true
uguid = "2.0.0"

[build-dependencies]
bindgen.workspace = true
