[package]
name = "vboot"
version = "0.1.0"
edition = "2018"

[dependencies]
goblin = { version = "0.4", default-features = false, features = ["pe32", "pe64"] }
log = "0.4"
printf-compat = { version = "0.1.1", default-features = false }
scroll = { version = "0.10", default-features = false }

[build-dependencies]
bindgen = "0.58.1"
camino = "1.0"
cc = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
