[advisories]
version = 2

[licenses]
allow = [
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Apache-2.0",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
skip = [
     { name = "bitflags", version = "1.3.2" },
     { name = "hashbrown", version = "0.12.3" },
     { name = "itertools", version = "0.9.0" },
     { name = "syn", version = "1.0.107" },
]

[sources]
unknown-git = "deny"
