[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
unlicensed = "deny"
allow = [
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Apache-2.0",
]

copyleft = "warn"
default = "deny"
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
skip = [
     { name = "bitflags", version = "1.3.2" },
     { name = "hashbrown", version = "0.12.3" },
     { name = "syn", version = "1.0.107" },
]

[sources]
unknown-git = "deny"
