[workspace]
members = ["crdyboot", "enroller", "libcrdy", "vboot", "xtask"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://chromium.googlesource.com/chromiumos/platform/crdyboot"
version = "1.0.0"

[workspace.dependencies]
log = { version = "0.4.0", default-features = false }
object = { version = "0.30.0", default-features = false, features = ["pe", "read_core", "unaligned"] }
uefi = { version = "0.23.0", default-features = false, features = ["alloc"] }
uefi-services = "0.20.0"

[profile.release]
overflow-checks = true
