[workspace]
members = ["crdyboot", "crdyshim", "enroller", "libcrdy", "vboot", "xtask"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://chromium.googlesource.com/chromiumos/platform/crdyboot"

[workspace.dependencies]
ed25519-compact = { version = "1.0.0", default-features = false }
log = { version = "0.4.0", default-features = false }
object = { version = "0.31.1", default-features = false, features = ["pe", "read_core", "unaligned"] }
sbat = "0.5.0"
uefi = { version = "0.25.0", default-features = false, features = ["alloc"] }
uefi-services = "0.22.0"

[profile.release]
overflow-checks = true
