[package]
name = "crdyboot_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
base64 = "0.13.0"
camino = { version = "1.0.7", features = ["serde1"] }
command-run = "1.1.1"
fatfs = "0.3.5"
# The latest fatfs release (0.3.5) is old, use git instead to pick up some fixes.
# TODO fatfs = { git = "https://github.com/rafalh/rust-fatfs.git", rev = "87fc1ed5074a32b4e0344fcdde77359ef9e75432" }
fehler = "1.0.0"
fs-err = "2.7.0"
gptman = { version = "0.8.3", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
tempfile = "3.3.0"
toml = "0.5.9"
