[package]
name = "crdyboot_tools"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
base64 = "0.13.0"
camino = { version = "1.0.7", features = ["serde1"] }
command-run = "1.1.1"
fehler = "1.0.0"
fs-err = "2.7.0"
serde = { version = "1.0.137", features = ["derive"] }
tempfile = "3.3.0"
toml = "0.5.9"
