[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
publish = false

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"
base64 = "0.13.0"
camino = { version = "1.0.9", features = ["serde1"] }
command-run = "1.1.1"
# The latest fatfs release (0.3.5) is old, use git instead to pick up some fixes.
fatfs = { git = "https://github.com/rafalh/rust-fatfs.git", rev = "4892fb1791b29616d8573235eb83644003d13791", default-features = false, features = ["std"] }
fs-err = "2.7.0"
gpt_disk_types = { version = "0.8.0", features = ["std"] }
gptman = { version = "1.0.0", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
tempfile = "3.3.0"
toml = "0.5.9"
