[package]
name = "enroller"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log = { workspace = true }
uefi = { workspace = true }
uefi-services = { workspace = true }

[features]
shim_verbose = []
