[package]
name = "enroller"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
log = "0.4.0"
uefi = { version = "0.23.0", default-features = false, features = ["alloc"] }
uefi-services = "0.20.0"

[features]
shim_verbose = []
