[package]
name = "enroller"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log = "0.4.0"
uefi = { version = "0.23.0", default-features = false, features = ["alloc"] }
uefi-services = "0.20.0"

[features]
shim_verbose = []
