[package]
name = "enroller"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
log = "0.4.0"
uefi = { version = "0.16.0", features = ["exts"] }
uefi-services = { version = "0.13.0", features = ["panic_handler"] }
