[package]
name = "libcrdy"

edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log = "0.4.0"
object = { version = "0.30.0", default-features = false, features = ["pe", "read_core", "unaligned"] }
uefi = { version = "0.23.0", default-features = false, features = ["alloc"] }
vboot = { path = "../vboot" }
