[package]
name = "libcrdy"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://chromium.googlesource.com/crdyboot"

[dependencies]
log = "0.4.0"
object = { version = "0.30.0", default-features = false, features = ["pe", "read_core", "unaligned"] }
uefi = { version = "0.23.0", default-features = false, features = ["alloc"] }
vboot = { path = "../vboot" }
