[package]
name = "libcrdy"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://chromium.googlesource.com/crdyboot"

[dependencies]
goblin = { version = "0.5.2", default-features = false, features = ["pe32", "pe64"] }
log = "0.4.0"
scroll = { version = "0.11.0", default-features = false }
uefi = { version = "0.16.0", features = ["exts", "ignore-logger-errors"] }
vboot = { path = "../vboot" }
