[package]
name = "crdyboot_tools"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
base64 = "0.13"
camino = "1.0"
command-run = "0.13"
fehler = "1.0"
fs-err = "2.6"
tempfile = "3.2"
